openapi: 3.0.0
info:
  title: KIWI - API REST v1
  contact: {}
  version: '1.0'
servers:
- url: http://localhost:3333
paths:
  /session:
    post:
      tags:
      - Session
      summary: Company authentication
      operationId: createSession
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
              - email
              - password
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
            example:
              email: company@gmail.com
              password:  '1234'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  company:
                    type: object
                    properties:
                      id: 
                        type: integer
                      name:
                        type: string
                      email:
                        type: string
                  token:
                    type: string
        default:
          description: Error
  /company:
    get:
      tags:
      - Company
      summary: List all
      operationId: getCompanies
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id: 
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
              example:
                [
                  {
                    id: 1,
                    name: Company 1,
                    email: company1@gmail.com
                  },
                  {
                    id: 2,
                    name: Company 2,
                    email: company2@gmail.com
                  }
                ]
        default:
          description: Error
    post:
      tags:
      - Company
      summary: Create
      operationId: createCompany
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
              - name
              - email
              - password
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
            example:
              name: company
              email: company@gmail.com
              password: '1234'
      responses:
        200:
          $ref: '#/components/responses/companyResponse'
        default:
          description: Error
  '/company/{id}':
    put:
      tags:
      - Company
      summary: Update
      operationId: updateCompany
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                oldPassword:
                  type: string
                password:
                  type: string
                  description: obrigatório caso preencha o campo `oldPassword`
                confirmPassword:
                  type: string
                  description: obrigatório caso preencha o campo `oldPassword`
            example:
              name: company
              email: company@gmail.com
              oldPassword: '1234'
              password: '4321'
              confirmPassword: '4321'
      responses:
        200:
          $ref: '#/components/responses/companyResponse'
        default:
          description: 'Error'
    delete:
      tags:
      - Company
      summary: Delete
      operationId: deleteCompany
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
              example:
                message: Company deleted
        default:
          description: Error
components:
  parameters:
    id:
      name: id
      in: path
      description: Company ID
      required: true
      schema:
        type: integer
  responses:
    companyResponse:
      description: Success
      content:
        application/json:
          schema:
            type: object
            properties:
              id: 
                type: integer
              name:
                type: string
              email:
                type: string
          example:
              id: 1
              name: company
              email: company@gmail.com
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
security:
- httpBearer: []
tags:
- name: Session
- name: Company
